#TODO ==== BUILT WITH QOONITY VERSION-1.0 - YINKA-ANTHONY-NKAY ON 2025-03-19T22:55:32.943709200
version = 0.1
[default.deploy.parameters]
stack_name = "todoTracker"
resolve_s3 = true
s3_prefix = "todoTracker"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "SecurityGroupId=\"\" Subnet1Id=\"\" Subnet2Id=\"\" DatabaseSecretName=\"\" DatabaseEndpoint=\"\""
image_repositories = []
profile = "qucoon"

